#! /bin/bash
code_exts="c cpp h hpp py"
grep_opts="-Hn"
OPTIND=1

while getopts "ht:i" opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;

        i)
            grep_opts+="i"
            ;;

        t)
            code_exts="$OPTARG"
            ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

snippet="$1"

for ext in $code_exts ; do
    find -type f -name "*.$ext" -exec grep "$grep_opts" "$snippet" {} \;
done
